[CI] Turn check on remaining JIT calls into an error (#77)

diff --git a/.github/workflows/CompileOrRun.yml b/.github/workflows/CompileOrRun.yml
--- a/.github/workflows/CompileOrRun.yml
+++ b/.github/workflows/CompileOrRun.yml
@@ -100,12 +100,12 @@ jobs:
           NUM_JIT_CALLS=$(echo "${JIT_CALLS}" | wc -l | xargs)
           if [[ -n "${JIT_CALLS}" ]]; then
               MSG="There are ${NUM_JIT_CALLS} remaining jit calls"
-              echo  "${MSG}:"
-              echo "::warning title=Remaining JIT Calls:: ${MSG}"
+              echo "::error title=Remaining JIT Calls:: ${MSG}"
               echo
               echo "----------"
               echo "${JIT_CALLS}"
               echo "----------"
+              exit 1
           fi
       - name: Upload MLIR modules
         uses: actions/upload-artifact@v4
